name: Trigger Other Repository Workflow

on:
  push:
    branches:
      - main
 

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    
    - name: Trigger workflow in Repository B
      run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/SrushtiVKhandade/target-demo/dispatches \
            -d '{"event_type":"custom_event"}'
